//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetail()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int PorductId { get; set; }
        public string PorductName { get; set; }
        public string ProductDescription { get; set; }
        public System.DateTime LastModified { get; set; }
        public System.DateTime AddedOn { get; set; }
        public decimal ProductPrice { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual CustomerDetail CustomerDetail1 { get; set; }
    }
}
